# Layout config
title: LilyPond Partitions
short_title: Partitions
description: >-
  Partitions built using LilyPond.
baseurl: /partitions
url: https://alexis.jeandeau.fr
repository: jeandeaual/partitions
lang: en-US
# Jekyll config
permalink: pretty
plugins:
  - jekyll-github-metadata
  - jekyll-minifier
  - jekyll-seo-tag
  - jekyll-timeago
jekyll-minifier:
  remove_intertag_spaces: true
  # exclude:
  #   - 'opds/*.xml'
  #   - 'opds/**/*.xml'
