name: deploy
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - '.github/workflows/lint.yml'
      - '.github/workflows/test.yml'
  # Can be triggered via the web UI or by running `curl -XPOST -u "${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/jeandeaual/partitions/actions/workflows/deploy.yml/dispatches --data '{"ref": "master"}'` from a GitHub Action
  workflow_dispatch:
    inputs: {}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Remove the .gitignore file
        run: rm -v .gitignore
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - name: Install the dependencies
        run: |
          # Required by pdftoimage
          sudo apt-get update && sudo apt-get -y install imagemagick poppler-utils
          bundle config set without 'development'
          bundle install --jobs 4 --retry 3
      - name: Download the PDFs
        env:
          GITHUB_TOKEN: ${{ secrets.GH_API_TOKEN }}
          GITHUB_USER: ${{ github.actor }}
        run: ruby download_pdfs.rb
      - name: Generate the OPDS feeds
        env:
          GITHUB_USER: ${{ github.actor }}
        run: ruby generate_opds.rb
      - name: Build the Jekyll site
        run: cd site && bundle exec jekyll build
        env:
          JEKYLL_ENV: production
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: site/_site
          CLEAN: true
          SINGLE_COMMIT: true
