name: Deploy
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Remove the .gitignore file
        run: rm -v .gitignore
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - name: Install the dependencies
        run: |
          bundle install --jobs 4 --retry 3 --without development
      - name: Download the PDFs
        env:
          GITHUB_TOKEN: ${{ secrets.GH_API_TOKEN }}
          GITHUB_USER: ${{ github.actor }}
        run: ruby ./download_pdfs.rb
      - name: Generate the OPDS feeds
        env:
          GITHUB_USER: ${{ github.actor }}
        run: ruby ./generate_opds.rb
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: site
          CLEAN: true
