name: lint
on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'README.md'
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Install the dependencies
        run: |
          # Required by pdftoimage
          sudo apt-get update && sudo apt-get -y install imagemagick poppler-utils
          bundle install --jobs 4 --retry 3 --without development
      - name: Run RuboCop
        run: bundle exec rubocop
